export const links = [
  { href: '/newIn', label: 'New In' },
  { href: '/sale', label: 'Sale' },
  { href: '/womenClothing', label: 'Women Clothing' },
  { href: '/curve', label: 'Curve' },
  { href: '/homeAndKitchen', label: 'Home & Kitchen' },
  { href: '/menClothing', label: 'Men Clothing' },
  { href: '/kids', label: 'Kids' },
  { href: '/jewelryAndAccessories', label: 'Jewelry & Accessories' },
  { href: '/underwearAndSleepwear', label: 'Underwear & Sleepwear' },
  { href: '/beautyAndHealth', label: 'Beauty & Health' },
  { href: '/shoes', label: 'Shoes' },
  { href: '/bagsAndLuggage', label: 'Bags & Luggage' },
  { href: '/homeTextiles', label: 'Home Textiles' },
  { href: '/sportsAndOutdoors', label: 'Sports & Outdoors' },
  { href: '/toysAndGames', label: 'Toys & Games' },
  { href: '/babyAndMaternity', label: 'Baby & Maternity' },
  { href: '/electronics', label: 'Electronics' },
  { href: '/toolsAndHomeImprovement', label: 'Tools & Home Improvement' },
  { href: '/officeAndSchoolSupplies', label: 'Office & School Supplies' },
  { href: '/appliances', label: 'Appliances' },
  { href: '/petSupplies', label: 'Pet Supplies' },
  { href: '/automotive', label: 'Automotive' },
];
