export const links = [
  { id: 'fkjffh1', href: '/newIn', label: 'New In' },
  { id: 'fkjffh2', href: '/sale', label: 'Sale' },
  { id: 'fkjffh3', href: '/womenClothing', label: 'Women Clothing' },
  { id: 'fkjffh4', href: '/curve', label: 'Curve' },
  { id: 'fkjffh5', href: '/homeAndKitchen', label: 'Home & Kitchen' },
  { id: 'fkjffh6', href: '/menClothing', label: 'Men Clothing' },
  { id: 'fkjffh7', href: '/kids', label: 'Kids' },
  {
    id: 'fkjffh8',
    href: '/jewelryAndAccessories',
    label: 'Jewelry & Accessories',
  },
  {
    id: 'fkjffh9',
    href: '/underwearAndSleepwear',
    label: 'Underwear & Sleepwear',
  },
  { id: 'fkjffh10', href: '/beautyAndHealth', label: 'Beauty & Health' },
  { id: 'fkjffh11', href: '/shoes', label: 'Shoes' },
  { id: 'fkjffh12', href: '/bagsAndLuggage', label: 'Bags & Luggage' },
  { id: 'fkjffh13', href: '/homeTextiles', label: 'Home Textiles' },
  { id: 'fkjffh14', href: '/sportsAndOutdoors', label: 'Sports & Outdoors' },
  { id: 'fkjffh15', href: '/toysAndGames', label: 'Toys & Games' },
  { id: 'fkjffh16', href: '/babyAndMaternity', label: 'Baby & Maternity' },
  { id: 'fkjffh17', href: '/electronics', label: 'Electronics' },
  {
    id: 'fkjffh18',
    href: '/toolsAndHomeImprovement',
    label: 'Tools & Home Improvement',
  },
  {
    id: 'fkjffh19',
    href: '/officeAndSchoolSupplies',
    label: 'Office & School Supplies',
  },
  { id: 'fkjffh20', href: '/appliances', label: 'Appliances' },
  { id: 'fkjffh21', href: '/petSupplies', label: 'Pet Supplies' },
  { id: 'fkjffh22', href: '/automotive', label: 'Automotive' },
];
