name: Test, Build, and Deploy

on:
  push:
    branches:
      - main

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.6.0'

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm setup
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH
        shell: bash
        env:
          SHELL: /bin/bash

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm run lint

      - name: Make build
        run: pnpm run build

      - name: Start Next.js Server
        run: pnpm start &
        env:
          NODE_ENV: development

      - name: Wait for Server to Start
        run: pnpm exec wait-on http://localhost:3000

      - name: Validate HTML
        run: pnpm run validate-html
  
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.53.1-noble

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.6.0'

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm setup
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH
        shell: bash
        env:
          SHELL: /bin/bash

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run coverage

  build:
    runs-on: ubuntu-latest
    needs: 
      - test
      - validate-html

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.6.0'

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm setup
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH
        shell: bash
        env:
          SHELL: /bin/bash

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm run lint

      - name: Make build
        run: pnpm run build

      - name: Run lighthouse
        run: |
          pnpm install -g @lhci/cli@latest
          pnpm run lighthouse
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Amplify
        run: aws amplify start-job --app-id ${{ secrets.AWS_APP_ID }} --branch-name main --job-type RELEASE --region ${{ secrets.AWS_REGION }}
